name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'  # Only trigger when files in the `charts/` directory change
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'  # Only trigger when files in the `charts/` directory change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Check if the commit is from the workflow itself
        run: |
          if [ "${GITHUB_ACTOR}" == "github-actions[bot]" ]; then
            echo "Skipping workflow because this is a commit made by the workflow itself."
            exit 0
          fi

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Get current chart version
        id: get_version
        run: |
          VERSION=$(grep 'version:' charts/nginx/Chart.yaml | awk '{print $2}')
          echo "Current chart version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment Chart Version
        id: increment_version
        run: |
          # Extract version components (major, minor, patch)
          IFS='.' read -r major minor patch <<< "${{ env.VERSION }}"
          
          # Increment the patch version
          patch=$((patch + 1))
          
          # Create the new version
          NEW_VERSION="$major.$minor.$patch"
          echo "New version: $NEW_VERSION"
          
          # Update the version in Chart.yaml
          sed -i "s/version: ${{ env.VERSION }}/version: $NEW_VERSION/" charts/nginx/Chart.yaml
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Updated Chart version to: $NEW_VERSION"

      - name: Package Helm Chart
        run: |
          helm package charts/nginx -d docs/ --version ${{ env.VERSION }}
          helm repo index docs --url https://ramyerubandi1.github.io/docs/

      - name: Commit and Push Changes
        run: |
          # Check if changes were made in the charts directory
          git diff --exit-code charts/nginx/Chart.yaml || {
            echo "Changes detected, committing and pushing new version."

            git config --global user.name "ramy"
            git config --global user.email "rmrbnd@gmail.com"

            git add charts/nginx/Chart.yaml docs/
            git commit -m "Auto-publish Helm chart version ${{ env.VERSION }}" || echo "No changes to commit"

            # Prevent workflow trigger loop by using GITHUB_TOKEN to push changes
            git push origin main || echo "No changes to push"
          }
